// ── Form ──

export type FormResult = 'W' | 'D' | 'L'

export interface TeamForm {
  last5: FormResult[]
  streak: string              // "3W", "2L", "1D"
}

// ── Stats ──

export interface TeamStats {
  goalsScored: number | null
  goalsConceded: number | null
  xG?: number | null
  xGA?: number | null
  shotsOnTarget: number | null
  possession: number | null         // % (football only)
  corners: number | null            // football only
  yellowCards: number | null         // football only
  cleanSheets: number | null
  bttsPct: number | null
  over25Pct: number | null
}

// ── Injuries ──

export interface Absence {
  name: string
  role: string                // "Нападающий", "Защитник", etc.
  reason: 'injury' | 'suspension' | 'personal'
  details?: string
  impact: 'key' | 'rotation' | 'minor'
}

// ── H2H ──

export interface H2HGame {
  date: string
  score: string               // "2:1"
  competition: string         // "РПЛ", "Кубок России"
}

// ── Context Factors ──

export interface ContextFactors {
  weather?: { temp: number; condition: string } | null
  restDays: { home: number | null; away: number | null }
  referee?: {
    name: string
    avgYellowCards: number
    penaltiesPerGame: number
  } | null
  recentTransfers?: string[]
}

// ── Odds ──

export interface BookmakerOdds {
  name: string
  values: Record<string, number>  // { "П1": 1.85, "X": 3.40, "П2": 4.20 }
}

// ═══════════════════════════════════════════
// MatchData — structured data from Perplexity
// ═══════════════════════════════════════════

export interface MatchData {
  context: {
    sport: 'football' | 'hockey' | 'basketball'
    homeTeam: string
    awayTeam: string
    competition: string       // "РПЛ", "КХЛ"
    round?: string            // "Тур 28", "1/4 финала"
    date: string
    time?: string
    venue?: string
    motivation: {
      home: { level: 'high' | 'medium' | 'low'; reason: string }
      away: { level: 'high' | 'medium' | 'low'; reason: string }
    }
  }

  form: {
    home: TeamForm
    away: TeamForm
  }

  h2h: {
    homeWins: number
    awayWins: number
    draws: number
    recentGames: H2HGame[]    // all games this season
  }

  stats: {
    home: TeamStats
    away: TeamStats
  }

  injuries: {
    home: Absence[]
    away: Absence[]
  }

  contextFactors: ContextFactors

  odds: {
    bookmakers: BookmakerOdds[]
  }
}

// ═══════════════════════════════════════════
// AnalysisReport — generated by Claude
// ═══════════════════════════════════════════

export interface AnalysisReport {
  sections: {
    formAnalysis: string      // 1-2 sentences
    statsAnalysis: string     // 1-2 sentences
    injuriesAnalysis: string  // 1-2 sentences
    contextAnalysis: string   // 1-2 sentences
    oddsAnalysis: string      // 1-2 sentences
  }

  odds: {
    average: Record<string, number>
    bestValue?: { market: string; bookmaker: string; odds: number }
    valueAssessment: {
      market: string
      indicator: 'underpriced' | 'fair' | 'overpriced'
    }[]
  }

  recommendation: {
    summary: string           // 1-2 sentences, 40-60 words
    confidence: 'high' | 'medium' | 'low'
    bets: {
      market: string          // "П1", "ТБ 5.5"
      reasoning: string       // 1-2 sentences
      confidence: 'high' | 'medium' | 'low'
      value: 'underpriced' | 'fair' | 'overpriced'
    }[]
  }
}

// ═══════════════════════════════════════════
// FullReport — combined for Supabase storage
// ═══════════════════════════════════════════

export interface FullReport {
  matchData: MatchData
  analysis: AnalysisReport
}
