// ── Form ──

export type FormResult = 'W' | 'D' | 'L'

export interface TeamForm {
  last5: FormResult[]
  streak: string              // "3W", "2L", "1D"
  homeRecord?: FormResult[]   // home team: last 4-5 at home; away team: ignored
  awayRecord?: FormResult[]   // away team: last 4-5 away; home team: ignored
}

// ── Stats ──

export interface TeamStats {
  goalsScored: number
  goalsConceded: number
  xG?: number
  xGA?: number
  shotsOnTarget: number
  possession: number          // %
  corners: number
  yellowCards: number
  cleanSheets: number         // out of last N
  bttsPct: number             // % matches where both scored
  over25Pct: number           // % matches with total > 2.5
}

// ── Injuries ──

export interface Absence {
  name: string
  role: string                // "Нападающий", "Защитник", etc.
  reason: 'injury' | 'suspension' | 'personal'
  details?: string
  impact: 'key' | 'rotation' | 'minor'
}

// ── H2H ──

export interface H2HGame {
  date: string
  score: string               // "2:1"
  competition: string         // "РПЛ", "Кубок России"
}

// ── Context Factors ──

export interface ContextFactors {
  weather?: { temp: number; condition: string }
  restDays: { home: number; away: number }
  referee?: {
    name: string
    avgYellowCards: number
    penaltiesPerGame: number
  }
  recentTransfers?: string[]
}

// ── Odds ──

export interface BookmakerOdds {
  name: string
  values: Record<string, number>  // { "П1": 1.85, "X": 3.40, "П2": 4.20 }
}

// ═══════════════════════════════════════════
// MatchData — structured data from first Claude call
// ═══════════════════════════════════════════

export interface MatchData {
  context: {
    sport: 'football' | 'hockey' | 'basketball'
    homeTeam: string
    awayTeam: string
    competition: string       // "РПЛ", "КХЛ"
    round?: string            // "Тур 28", "1/4 финала"
    date: string
    time?: string
    venue?: string
    motivation: {
      home: { level: 'high' | 'medium' | 'low'; reason: string }
      away: { level: 'high' | 'medium' | 'low'; reason: string }
    }
  }

  form: {
    home: TeamForm
    away: TeamForm
  }

  h2h: {
    homeWins: number
    awayWins: number
    draws: number
    recentGames: H2HGame[]
  }

  stats: {
    home: TeamStats
    away: TeamStats
  }

  injuries: {
    home: Absence[]
    away: Absence[]
  }

  contextFactors: ContextFactors

  odds: {
    bookmakers: BookmakerOdds[]
  }
}

// ═══════════════════════════════════════════
// AnalysisReport — generated by second Claude call
// ═══════════════════════════════════════════

export interface AnalysisReport {
  sections: {
    formAnalysis: string      // 2-3 sentences
    statsAnalysis: string     // 2-3 sentences
    injuriesAnalysis: string  // 1-2 sentences
    contextAnalysis: string   // 1-2 sentences
    oddsAnalysis: string      // 1-2 sentences
  }

  odds: {
    average: Record<string, number>
    bestValue?: { market: string; bookmaker: string; odds: number }
    valueAssessment: {
      market: string
      indicator: 'underpriced' | 'fair' | 'overpriced'
    }[]
  }

  recommendation: {
    summary: string           // 1-2 sentences
    confidence: 'high' | 'medium' | 'low'
    bets: {
      market: string          // "П1", "ТБ 2.5", "BTTS Да"
      reasoning: string
      confidence: 'high' | 'medium' | 'low'
      value: 'underpriced' | 'fair' | 'overpriced'
    }[]
  }
}

// ═══════════════════════════════════════════
// FullReport — combined for Supabase storage
// ═══════════════════════════════════════════

export interface FullReport {
  matchData: MatchData
  analysis: AnalysisReport
}
